name: Build Static Qt (Windows)

on:
  workflow_dispatch:

jobs:
  build-qt:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install -y strawberryperl winflexbison ninja 7zip

      - name: Download Qt 5.15.2 source
        run: |
          curl -LO https://download.qt.io/archive/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.zip
          7z x qt-everywhere-src-5.15.2.zip -y > nul

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure Qt (static)
        run: |
          cd qt-everywhere-src-5.15.2
          cmd /c "configure.bat -static -release -platform win32-msvc -opensource -confirm-license -prefix %CD%\qt-static -qt-zlib -qt-libpng -qt-webp -qt-libjpeg -qt-freetype -no-opengl -skip qt3d -skip qtactiveqt -skip qtandroidextras -skip qtcharts -skip qtconnectivity -skip qtdatavis3d -skip qtdeclarative -skip qtdoc -skip qtgamepad -skip qtlocation -skip qtlottie -skip qtmacextras -skip qtmultimedia -skip qtnetworkauth -skip qtpurchasing -skip qtquick3d -skip qtquickcontrols -skip qtquickcontrols2 -skip qtquicktimeline -skip qtremoteobjects -skip qtscript -skip qtsensors -skip qtspeech -skip qtsvg -skip qtwayland -skip qtwebglplugin -skip qtwebview -skip webengine -make libs -nomake tools -nomake examples -nomake tests"
      - name: Build and install Qt
        run: |
          cd qt-everywhere-src-5.15.2
          nmake
          nmake install

      - name: Package Qt
        run: |
          cd qt-everywhere-src-5.15.2
          7z a -tzip qt-static.zip .\qt-static\*

      - name: Upload artifact (temporary)
        uses: actions/upload-artifact@v4
        with:
          name: qt-static-win
          path: qt-everywhere-src-5.15.2/qt-static.zip
