name: Build Static Qt (Windows)

on:
  workflow_dispatch:
    inputs:
      qt_version:
        description: 'Qt version (e.g., 6.9.1)'
        required: true
        default: '6.9.1'

      # Only the last version is hosted usually, it will fail to download once there is a new version released.
      openssl_version:
        description: 'OpenSSL version (e.g., 3_5_2)'
        required: true
        default: '3_5_2'

jobs:
  build-qt:
    runs-on: windows

    env:
      QT_VERSION: ${{ inputs.qt_version }}
      OPENSSL_VERSION: ${{ inputs.openssl_version }}
      QT_INSTALL_DIR: "C:/Qt/${{ QT_VERSION }}-qt-static-win"
      OPENSSL_INSTALL_DIR: ${{ github.workspace }}\OpenSSL

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          choco install -y strawberryperl winflexbison ninja 7zip

      - name: Download Qt Source
        shell: bash
        run: |
          QT_MINOR_VERSION=$(echo "${{ env.QT_VERSION }}" | cut -d. -f1,2)
          echo "QT_MINOR_VERSION=$QT_MINOR_VERSION" >> $GITHUB_ENV
          curl -LO https://download.qt.io/official_releases/qt/$QT_MINOR_VERSION/${{ env.QT_VERSION }}/single/qt-everywhere-src-${{ env.QT_VERSION }}.zip
          7z x qt-everywhere-src-${{ env.QT_VERSION }}.zip -y > /dev/null

      - name: Download and Extract OpenSSL (prebuilt)
        run: |
          $installer = "Win64OpenSSL-${{ env.OPENSSL_VERSION }}.exe"
          Invoke-WebRequest -Uri "https://slproweb.com/download/$installer" -OutFile $installer
          Start-Process -Wait -FilePath $installer -ArgumentList "/silent", "/verysilent", "/sp-", "/suppressmsgboxes", "/DIR=${{ env.OPENSSL_INSTALL_DIR }}"

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      # Relocatable build messes up our static build -> using prefixed -> Qt build needs to go into "C:/Qt/${{ env.QT_VERSION }}-qt-static-win
      - name: Configure Qt with CMake (static + OpenSSL)
        shell: bash
        run: |
          rm -rf "${{ env.QT_INSTALL_DIR }}"
          mkdir "${{ env.QT_VERSION }}-build"
          cd "${{ env.QT_VERSION }}-build"
          ../qt-everywhere-src-${{ env.QT_VERSION }}/configure -static -static-runtime -debug-and-release -platform win32-msvc \
            -opensource -confirm-license -prefix "${{ env.QT_INSTALL_DIR }}" \
            -qt-zlib -qt-libjpeg -qt-libpng -qt-freetype -qt-pcre -qt-harfbuzz \
            -skip qt3d -skip qtactiveqt -skip qtcharts -skip qtcoap -skip qtconnectivity \
            -skip qtdeclarative -skip qtlocation -skip qtgraphs -skip qtdatavis3d \
            -skip qtdoc -skip qtlottie -skip qtmqtt -skip qtnetworkauth -skip qtopcua \
            -skip qtpositioning -skip qtquick3d -skip qtquick3dphysics -skip qtquicktimeline \
            -skip qtquickcontrols2 -skip qtquickvectorimage -skip qtquickeffects \
            -skip qtremoteobjects -skip qtscxml -skip qtsensors -skip qtserialbus \
            -skip qtserialport -skip qtvirtualkeyboard -skip qtwayland \
            -skip qtwebchannel -skip qtwebengine -skip qtwebview -skip qtquickeffectmaker \
            -skip qtspeech -skip qthttpserver \
            -openssl-linked -I "${{ env.OPENSSL_INSTALL_DIR }}/include" -L "${{ env.OPENSSL_INSTALL_DIR }}/lib/VC/x64/MT" OPENSSL_LIBS="-lUser32 -lAdvapi32 -lGdi32 -lCrypt32 -lws2_32 -lssl_static -lcrypto_static" \
            -nomake examples -nomake tests \
            -- -DCMAKE_EXE_LINKER_FLAGS_INIT="/LIBPATH:C:/Qt/${QT_VERSION}-qt-static-win/lib" -DCMAKE_SHARED_LINKER_FLAGS_INIT="/LIBPATH:C:/Qt/${QT_VERSION}-qt-static-win/lib"

      - name: Build Qt (Debug + Release)
        shell: bash
        run: |
          cd "${{ env.QT_VERSION }}-build"
          cmake --build . --parallel --config Release
          cmake --build . --parallel --config Debug
      
      - name: Install Qt (Debug + Release)
        shell: bash
        run: |
          cd "${{ env.QT_VERSION }}-build"
          cmake --install . --config Release
          cmake --install . --config Debug

      # Packe the OpenSSL static libs with Qt, so we load them automatically.
      - name: Copy OpenSSL static libs
        shell: bash
        run: |
          cp "${{ env.OPENSSL_INSTALL_DIR }}/lib/VC/x64/MT/libssl_static.lib" "${{ env.QT_INSTALL_DIR }}/lib/libssl.lib"
          cp "${{ env.OPENSSL_INSTALL_DIR }}/lib/VC/x64/MT/libcrypto_static.lib" "${{ env.QT_INSTALL_DIR }}/lib/libcrypto.lib"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.QT_VERSION }}-qt-static-win
          path: "${{ env.QT_INSTALL_DIR }}"
          include-hidden-files: true
